# site title
title: 学习笔记归档

# github user
user: hsipeng

# issue repository
repository: note

# multi-author
authors: hsipeng

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 3#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

# posts per page
perpage: 5
