name: CI

on: [issues]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@master
    - name: install dependencies
      run: |
        pip3 install setuptools --user
        pip3 install PyGithub --user
        pip3 install wordcloud --user
        pip3 install matplotlib --user
    - name: run python script
      env:
        GITHUB_LOGIN: ${{ secrets.USER_NAME }}
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.CURR_REPOSITORY }}
      run: python3 main_github_action.py
    - name: config git info
      run: |
        git config --global user.email "${{ secrets.USER_EMAIL }}"
        git config --global user.name "${{ secrets.USER_NAME }}"
    - name: commit change
      run: |
        git checkout master
        git add .
        git commit -m "Update from Github Action"
    - name: push change
      env:
        GITHUB_LOGIN: ${{ secrets.USER_NAME }}
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_REPOSITORY: ${{ secrets.CURR_REPOSITORY }}
      run: |
        git push https://$GITHUB_LOGIN:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
    - name: done
      run: echo 'done'
